### ISSUE TITLE
Panic with .IsNumberMatch

### ISSUE THREAD

**Issue by AugustDev** [nyaruka/phonenumbers#60]
I am trying to compare UK numbers without country code and end up with panic.

```go
package main

import (
	"fmt"

	"github.com/nyaruka/phonenumbers"
)

func main() {
	res := phonenumbers.IsNumberMatch("07598765432", "07598765432")
	fmt.Println(res)
}
```

This results in following panic

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x117d130]

goroutine 1 [running]:
github.com/nyaruka/phonenumbers.maybeExtractCountryCode(0xc00015de38, 0xb, 0x0, 0xc00017a1c0, 0xc00015de00, 0x0, 0x10138f7, 0x1594638, 0x203000)
        /Users/myuser/go/pkg/mod/github.com/nyaruka/phonenumbers@v1.0.56/phonenumbers.go:2597 +0x800
github.com/nyaruka/phonenumbers.parseHelper(0x11dd979, 0xb, 0x0, 0x0, 0xc000320000, 0x0, 0xc000010ab0, 0xffffffffffffffff)
        /Users/myuser/go/pkg/mod/github.com/nyaruka/phonenumbers@v1.0.56/phonenumbers.go:2890 +0x317
github.com/nyaruka/phonenumbers.IsNumberMatch(0x11dd979, 0xb, 0x11dd979, 0xb, 0xc0000200b8)
        /Users/myuser/go/pkg/mod/github.com/nyaruka/phonenumbers@v1.0.56/phonenumbers.go:3142 +0x155
main.main()
        /Users/myuser/Projects/go/phone-numbers/main.go:10 +0x48
exit status 2
```

go version go1.14.4 darwin/amd64

**Comment by nicpottier** [comment]
Thanks for reporting, fixed (and added unit tests) in v1.0.57
